src/Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from accounts.views import (login_view, register_view, logout_view)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^posts/$', "<appname>.views.<function_name>"),

    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("blog.urls", namespace='posts')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)


urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe
from markdown_deux import markdown
from django.contrib.contenttypes.models import ContentType

from comments.models import Comment
from .utils import get_read_time

# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_loacation(instance, filename):
    return "%s/%s" %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_loacation, null=True, blank=True,
            height_field="height_field",
            width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    read_time = models.IntegerField(default=0) #models.TimeField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_show = get_read_time(html_string)
        instance.read_time = read_time_show

pre_save.connect(pre_save_post_reciever, sender=Post)

src/blog/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "content",
            "draft",
            "publish",
        ]

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block head_title %}Blog{% endblock head_title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="shortcut icon" href='{% static "images/favicon.ico" %}'/>
    <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel='stylesheet' href='{% static "css/base.css" %}' />
    <style media="screen">
    {% block style%}

    {% endblock style %}
    </style>
    {% block head_extra %} {% endblock head_extra %}
    </head>
    <body>
      <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        {% include "messages_display.html" %}
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand " href="{% url "posts:list" %}" style="color: black">Blog Home</a>
          </div>
          <ul class="nav navbar-nav">

            {% block post_detail_link %}

            {% endblock %}
            </ul>
             <ul class="nav navbar-nav navbar-right">
            {% if not request.user.is_authenticated %}

            <li><a href="{% url "register" %}"><span class="glyphicon glyphicon-user" style="color: black"></span> Sign Up</a></li>
            <li><a href="{% url "login" %}"><span class="glyphicon glyphicon-log-in" style="color: black"></span> Login</a></li>
            {% else %}
            <li><a href="{% url "logout" %}" style="color: black">Logout</a></li>
            {% endif %}
          </ul>

        </div>
      </nav>
      <hr/>

      {% block content %}

      {% endblock %}
  </div>
  <script
    src="http://code.jquery.com/jquery-1.12.4.min.js"
    integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
    crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
  integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
  crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>



  <script type="text/javascript">
    $(document).ready(function () {
      $(".content-markdown").each(function () {
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
      })

      $(".post-detail-item img").each(function () {
        $(this).addClass("img-responsive");
      })

      // preview-title
      // preview-content

      var contentInput = $("#id_content");

      function setContent(value) {
        var markedContent = marked(value)
          $("#preview-content").html(markedContent)
          $("#preview-content img").each(function () {
            $(this).addClass("img-responsive")
          })
      }
      setContent(contentInput.val())

      contentInput.keyup(function() {
        var newContent = $(this).val()
        setContent(newContent)
      })

      var titleInput = $("#id_title");

      function setTitle(value) {
        $("#preview-title").text(value)
      }
      setTitle(titleInput.val())

      titleInput.keyup(function() {
        var newContent = $(this).val()
        setTitle(newContent)
      })

      $(".comment-reply-btn").click(function (event) {
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
      })


     })
  </script>
  </body>
  <footer class="footer-distributed">

			<div class="footer-left">



				<p class="footer-company-name" style="font-size: 30px">Lalit Kumar &copy; 2017</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p>IIIT Vadodara<span> Gandhinagar, Gujarat</span></p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+919712618438</p>
				</div>

				<div>
					<i class="fa fa-envelope" aria-hidden="true"></i>
					<p><a href="mailto:lalitkumar.meena.lk@gmail.com">lalitkumar.meena.lk@gmail.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<strong style="font-size: 20px">About Myself</strong>
          <br/>
          <br/>
					I am a student of IIIT Vadodara, Gandhinagar, Gujarat. I believe that
          " ThE FutURe bElonGs to those who bElieve in thEir beAutiFul DREAMS....."
				</p>

				<div class="footer-icons">

					<a href="https://www.facebook.com/profile.php?id=100004428344426"><i class="fa fa-facebook"></i></a>
					<a href="https://twitter.com/lalitkumarmee10"><i class="fa fa-twitter"></i></a>
					<a href="https://www.linkedin.com/in/lalitmee/"><i class="fa fa-linkedin"></i></a>
					<a href="https://github.com/lalitmee"><i class="fa fa-github"></i></a>

				</div>

			</div>

		</footer>
</html>

src/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}


<style media="screen">
{% block style%}

{% endblock style %}
</style>
{% block content %}
{{ object }}

<div class="col-sm-6 col-sm-offset-3">


    <p>{{ comment.content }}</p>
    <footer class="blockquote-footer">
      via {{ comment.user }} | {{ comment.timestamp| timesince }} ago |
      {% if comment.children.count > 0 %}
      {{ comment.children.count }}
      Comment{% if comment.children.count > 1 %}s
      {% endif %} |
      {% endif %}
      {% if request.user == comment.user %}
      <a href="{{ comment.get_delete_url }}">Delete</a>
      {% endif %}
    </footer>
    <hr/>

    <div >
     {% for child_comment in comment.children %}
     <blockquote class="blockquote">
      <p class="mb-0">{{ child_comment.content }}</p>
      <footer class="blockquote-footer">
        via {{ child_comment.user }} | {{ child_comment.timestamp| timesince }} ago |
        {% if request.user == child_comment.user %}
        <a href="{{ child_comment.get_delete_url }}">Delete</a>
        {% endif %}
      </footer>
    </blockquote>
    {% endfor %}
    {% if request.user.is_authenticated %}
      <form class="" action="." method="POST"> {% csrf_token %}
          {{ form|crispy }}
          <input type="hidden" name="parent_id" value="{{ comment.id }}">
          <input class="btn btn-default" type="submit" name="" value="Reply">
      </form>
      {% else %}
      <p>You must login to comment</p>
      {% endif %}
    </div>

    <hr/>

</div>
{% endblock content %}

src/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}


<style media="screen">
{% block style%}

{% endblock style %}
</style>
{% block content %}

<div class="container">
<div class="col-sm-6 col-sm-offset-3">
<h1>Confirm Delete</h1>
      <form class="" action="." method="POST"> {% csrf_token %}
          <p>Are you sure you want to delete : "{{ object.content }}"?</p>
          <input class="btn btn-warning" type="submit" name="" value="Confirm">
          <a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
      </form>
    </div>

    <hr/>

</div>
{% endblock content %}

src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load staticfiles %}
<style media="screen">
{% block style%}

{% endblock style %}
</style>

{% block content %}
<div class="col-sm-6 col-sm-offset-3">

    <h1>{{ title }}</h1>
    <hr>
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" class="btn btn-default" name="" value="{{ title }}"/>
    </form>
    </div>
</div>
{% endblock content %}

src/templates/messages_display.html
{% if messages %}
<div class="message">
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
</div>
{% endif %}

src/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}{{ instance.title }} | {{ block.super }}{% endblock head_title %}



{% block content %}
<div class="container">
<div class="col-sm-10 col-sm-offset-2">
  <hr/>
  {% if instance.image %}
<img src="{{ instance.image.url }}" class="img-responsive" alt="">
{% endif %}
    <h1 >{{ title }}
      <small>{% if instance.draft %}
        <span style="color:red;">Draft </span>
        {% endif %}{{ instance.publish }}
        <small>
          <p>Read Time : {% if instance.read_time <= 1 %} < 1 minute
            {% else %}
            {{ instance.read_time }}
            minutes
            {% endif %}
          </p>
        </small>
      </small>
      </h1>
    {% if instance.user.get_full_name %}
    <p>Author : {{ instance.user.get_full_name }}</p>
    {% endif %}
    <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}"
    data-layout="button_count" data-action="like" data-size="small"
    data-show-faces="true" data-share="true"></div></p>
    <hr>
    <div>

      <div class="row">
        <div class="col-sm-10  ">
          <div class="post-detail-item ">{{ instance.get_markdown }}</div>
          <hr/>
          <br/>
          <div>
            <p class="lead">Comments</p>
            {% if request.user.is_authenticated %}
            <form action="." method="POST"> {% csrf_token %}
                {{ comment_form|crispy }}
                <input class="btn btn-default" type="submit" name="" value="Post comment">
            </form>
            {% else %}
            <p>You must login to comment</p>
            {% endif %}
            <hr>
          {% for comment in comments %}
            <blockquote class="blockquote">
            <p class="mb-0">{{ comment.content }}</p>
            <footer class="blockquote-footer">
              via {{ comment.user }} | {{ comment.timestamp| timesince }} ago |
              {% if comment.children.count > 0 %}
              {{ comment.children.count }}
              Comment{% if comment.children.count > 1 %}s
              {% endif %} |
              {% endif %}
              <a class="comment-reply-btn" href="#">Reply</a> |
              <a class="" href="{{ comment.get_absolute_url }}">Thread</a>
            </footer>

            <div class="comment-reply">
              {% for child_comment in comment.children %}
              <blockquote class="blockquote">
              <p >{{ child_comment.content }}</p>
              <footer class="blockquote-footer">
                via {{ child_comment.user }} | {{ child_comment.timestamp| timesince }}
              </footer>
            </blockquote>
            {% endfor %}
            {% if request.user.is_authenticated %}
              <form class="" action="." method="POST"> {% csrf_token %}
                  {{ comment_form|crispy }}
                  <input type="hidden" name="parent_id" value="{{ comment.id }}">
                  <input class="btn btn-default" type="submit" name="" value="Reply">
              </form>
              {% else %}
              <p>You must login to comment</p>
              {% endif %}
            </div>


          </blockquote>
            <hr/>
            {% endfor %}
           </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% load staticfiles %}
<style media="screen">
{% block style%}

{% endblock style %}
</style>

{% block content %}
<div class="col-sm-6">
  <div class="thumbnail">
    <h1>Preview</h1>
    <hr>
    <div class="content-preview">
      <h3 id="preview-title"></h3>
      <p id="preview-content"></p>
    </div>
  </div>
</div>

<div class="col-sm-6">
<div class="post_create">
    <h1>Form</h1>
    <hr>
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" class="btn btn-default" name="" value="create post"/>
    </form>
    </div>
</div>
{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}

{% load staticfiles %}

{% block head_title %} {{ block.super }}{% endblock head_title %}

<style media="screen">
{% block style%}

{% endblock style %}
</style>
</head>
<body>
  {% block content%}
  <div class="col-sm-8 col-sm-offset-2">

  
  <form class="row" action="" method="GET">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="input-group">
        <input class="form-control"
        type="text"
        placeholder="Search for the post"
        name="q" value="{{ request.GET.q }}">
        <span class="input-group-btn">
          <button class="btn btn-default"
          type="submit" style="font-weight: 50px">Search <i class="fa fa-search" aria-hidden="true"></i>
        </button>
        </span>
      </div>
      <hr/>
    </div>
  </form>

  {% for obj in objects_list %}
  <div class="row">
  <div class="col-sm-12 ">
    <div class="thumbnail">
      {% if obj.image %}
    <img src="{{ obj.image.url }}" class="img-responsive" alt="">
    {% endif %}
      <div class="caption post-detail-item">
        {% if obj.draft %}
        <h3>Staff Only : Draft</h3>
        {% endif %}
        <h1><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a><small> {{ obj.publish }} </small> 

           {% if obj.user.get_full_name %}
           <p><strong>Author</strong> : {{ obj.user.get_full_name }}</p>
           {% endif %}
           </h1> 
           <hr/>
        {{ obj.get_markdown | truncatechars_html:200 }}
        <hr/>
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">Read More</a></p>
      </div>
    </div>
    <hr/>
  </div>
</div>
  {% endfor %}

  <div class="pagination">
    <span class="step-links">
        {% if objects_list.has_previous %}
            <a href="?{{ page_request_var }}={{ objects_list.previous_page_number }}{% if request.GET.q %}
            &q={{ request.GET.q }} {% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ objects_list.number }} of {{ objects_list.paginator.num_pages }}.
        </span>

        {% if objects_list.has_next %}
            <a href="?{{ page_request_var }}={{ objects_list.next_page_number }}{% if request.GET.q %}
            &q={{ request.GET.q }} {% endif %}">next</a>
        {% endif %}
    </span>
</div>
  </div>
  {% endblock content %}